"""empty message

Revision ID: 36254b5538a5
Revises: 
Create Date: 2017-10-12 18:59:26.237782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36254b5538a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
