"""empty message

Revision ID: 74891d66d692
Revises: 36254b5538a5
Create Date: 2017-10-12 20:08:49.189170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74891d66d692'
down_revision = '36254b5538a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
